### ISSUE TITLE
Error - Both in Docker and while running Main.py  

### ISSUE THREAD

**Issue by Curiosity007** [iGavroche/BrainChulo#25]
I can start the app via docker method. But while uploading/conversation etc. giving errors 

```
backend_1   | INFO:     172.18.0.1:41944 - "OPTIONS /conversations HTTP/1.1" 400 Bad Request
backend_1   | INFO:     172.18.0.1:33130 - "POST /conversations/null/files HTTP/1.1" 422 Unprocessable Entity
backend_1   | INFO:     172.18.0.1:44614 - "OPTIONS /conversations/null/messages HTTP/1.1" 400 Bad Request
```
So, docker method is not working. However, I can see the frontend GUI. 

The only change I did in docker-compose.yaml is to comment the #network_mode: "host" because I was getting this error - 

`ERROR: for brainchulo_backend_1  "host" network_mode is incompatible with port_bindings`

However, I actually want to use the python main.py variation to give me flexibility. When I run the script, i can see port 7865 is running and I can see the webpage. However, when I try to run localhost:5173, I am not getting any interface. How do I run using only main.py?

**Comment by iGavroche** [comment]
Hi @Curiosity007 , please click on your avatar in the top navigation bar and click "Clear Chat History". This will reset the database.
Currently, because we lack migrations, when we make schema updates you should run this reset after pulling the latest changes.

**Comment by iGavroche** [comment]
By any chance, did you rebuild the image as such before running it?
`docker compose up --build`

**Comment by iGavroche** [comment]
thanks for letting me know. I'll boot up Windows and give it a shot when HuggingFace fixes their network issues. Right now, building the container image doesn't work.

**Comment by paolorechia** [comment]
Working fine here too. However, I don't see the OPTIONS requests. Could it be that CORS is an issue because you're using ngrok?

![image](https://github.com/iGavroche/BrainChulo/assets/5386983/2a7fc3ac-aac2-47f6-8d41-19bc1bc09101)

**Comment by iGavroche** [comment]
That's a great point. @Curiosity007 , if you use ngrok, make sure to add the url to the list of allowed origins.

**Comment by iGavroche** [comment]
looks like you should update 0.0.0.0 to maybe localhost or 127.0.0.1? I think the issue is now that your setup cannot access Ooba.
If you want to fast-track this issue you should join our Discord so we can discuss.
